FROM python:3.8-slim

# layer caching for faster builds
COPY requirements.txt /
RUN pip install -r /requirements.txt

ADD . /celery_worker
WORKDIR /celery_worker

CMD celery -A tasks.app worker -B --loglevel=INFO
