# Dockerfile для тестов
FROM python:3.10-slim

RUN pip install pytest requests aiohttp pytest-asyncio

COPY tests/ /app/tests/

WORKDIR /app/tests/

# Запускает эту команду чтобы контейнер оставался активным
CMD ["sleep", "infinity"]
